project:
  type: website
  output-dir: _site
  resources: # Can just specify which folders need to be rendered, see https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
    - "*.md"
    - "docs/**/*.md"
  render:
    # Render
    - "index.md"
    - "docs/**/*.md"
    # Do not render
    - "!_under_development/**"
    - "!slides/**"
    - "!docs/infrastructure/getting_started.md"
    - "!docs/infrastructure/VPS_SSH_connect.md"
    - "!docs/infrastructure/giving_sudo_privilages.md"
    - "!docs/infrastructure/configure_passwordless_login.md"
    - "!docs/infrastructure/gitlab/runner_python.md"
    - "!docs/infrastructure/gitlab/runner_docker.md"
    - "!docs/software/documentation.md"
    - "!docs/software/containers/podman.md"
execute: 
  freeze: true # When freeze: true is set, it tells Quarto to "freeze" the execution of code chunks.

website:
  title: "DCC Guides"
  # google-analytics: "UA-XXXXXXXX"
  # cookie-consent: true
  #
  site-url: https://tu-delft-dcc.github.io/
  repo-url: https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io/
  issue-url: https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io/issues/new/choose
  repo-actions: [issue]
  page-navigation: true
  page-footer:
    left: By TU Delft Digital Competence Centre. Content on this site is licensed under a [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) license.
    right: 
          If you find this content useful, please consider giving us a star on GitHub.
          <script async defer src="https://buttons.github.io/buttons.js"></script>
          <a class="github-button" href="https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io" data-icon="star" data-size="small" data-show-count="false" aria-label="Star TU-Delft-DCC/TU-Delft-DCC.github.io on GitHub">Star</a>   
  bread-crumbs: true # Breadcrumbs in Quarto websites are a type of secondary navigation that shows the user's current location within the site hierarchy
  navbar:
    logo: docs/img/logo.png
    collapse-below: lg # It determines at which screen size the navbar should collapse into a mobile-friendly format (typically a hamburger menu)
    left:
      - href: docs/community/dcc.md
        text: About the DCC
      # - href: name.md
      #   text: Contact
      - href: CONTRIBUTING.md
        text: Contributing
      - href: CODE_OF_CONDUCT.md
        text: Code of Conduct
      # - href: name.md
      #   text: FAQ   
    tools:
      - icon: github
        href: https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io/
        text: DCC GitHub
  sidebar:
    style: "docked"
    collapse-level: 2
    align: left
    contents:
      - section: "⚙️ **Computing Infrastructure**"
        contents:
          - href: docs/infrastructure/intro_servers.md
            text: Remote servers
            contents:
              - href: docs/infrastructure/VPS_request.md
                text: Request a VPS
              - href: docs/infrastructure/VPS_SSH.md
                text: Configure SSH Tunneling
              - href: docs/infrastructure/moving_data.md
                text: Moving data to your server
              - href: docs/infrastructure/VPS_SSL_Certs.md
                text: Configure SSL certificates
              - href: docs/infrastructure/apache_webserver.md
                text: Setting up an Apache web server
          - href: docs/infrastructure/gitlab/gitlab_intro.md
            text: TU Delft GitLab
            contents:
              - href: docs/infrastructure/gitlab/gitlab_groups.md
                text: Creating GitLab groups
              - href: docs/infrastructure/gitlab/gitlab_transfer_ownership.md
                text: Transfer ownership of a GitLab repository
              - href: docs/infrastructure/gitlab/gitlab_docker.md
                text: Continuous Integration with GitLab
              - href: docs/infrastructure/gitlab/runner_matlab.md
                text: Setting up a Gitlab runner for MATLAB
      - section: "🗃️ **Data Management**"
        contents:
          - href: docs/data/getting_started.md
            text: Getting started
          - href: docs/data/fair.md
            text: FAIR Data
            contents:
              - href: docs/data/publishing.md
                text: Prepare data for publishing
          - href: docs/data/storage_options.md
            text: TU Delft Data storage
            contents:
              - href: docs/data/project_drive_request.md
                text: Request Project Drive space
              - href: docs/data/project_drive_mounting.md
                text: Mount Project Drive on Server
              - href: docs/data/sync_unison.md
                text: Sync with Project Drive and SURFDrive with Unison
      - section: "💻 **Research Software**"
        contents:
          - href: docs/software/getting_started.md
            text: Getting started
          - href: docs/software/fair.md
            text: FAIR Software
            contents:
              - href: docs/software/checklist.md
                text: FAIR checklist for research software
              - href: docs/software/project_cards.md
                text: FAIR assessment cards
              - href: docs/software/software_management_plan.md
                text: Software management plan
              - url: https://tu-delft-dcc.github.io/FAIR4RS/
                text: FAIR for Research Software Program Spring 2023
          - href: docs/software/testing_intro.md
            text: Software testing
            contents:
              - href: docs/software/testing_matlab.md
                text: Testing with MATLAB
          - href: docs/software/git/intro.md
            text: Version control with Git
            contents:
              - href: docs/software/git/branch_management.md
                text: Branch management
          - href: docs/software/containers/intro.md
            text: Working with containers
            contents:
              - href: docs/software/containers/docker_gui.md
                text: Using a docker container with a GUI
      - section: "📖 **Resources**"
        contents:
          - href: docs/resources/courses.md
            text: Courses and workshops
          - href: docs/resources/curriculum.md
            text: Research Software Curriculum
          - href: docs/resources/tools.md
            text: Tools
          
highlight-style: pygments
format:
  html:
    theme: 
      light: cosmo
      dark: solar
      # dark: [cosmo, themes/theme-dark.scss]
    css: themes/custom.css
    toc: true
    toc-location: right