project:
  type: website
  output-dir: _site
  resources: # Can just specify which folders need to be rendered, see https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
    - "*.md"
    - "docs/**/*.md"
  render:
    # Render
    - "index.md"
    - "CONTRIBUTING.md"
    - "CODE_OF_CONDUCT.md"
    - "docs/**/*.md"
    # Do not render
    - "!_under_development/**"
    - "!slides/**"
    - "!docs/infrastructure/getting_started.md"
    - "!docs/infrastructure/VPS_SSH_connect.md"
    - "!docs/infrastructure/giving_sudo_privilages.md"
    - "!docs/infrastructure/configure_passwordless_login.md"
    - "!docs/infrastructure/gitlab/runner_python.md"
    - "!docs/infrastructure/gitlab/runner_docker.md"
    - "!docs/software/documentation.md"
    - "!docs/software/containers/podman.md"
    - "!docs/data/to_be_deleted_publishing.md"
execute: 
  freeze: true # When freeze: true is set, it tells Quarto to "freeze" the execution of code chunks.

website:
  # title: "DCC Guides"
  # google-analytics: "UA-XXXXXXXX"
  # cookie-consent: true
  #
  announcement: 
    icon: pencil
    dismissable: true
    content: "**Information!** We are now actively updating our content. Please be aware that content and locations are subject to change. Thank you for your patience!"
    type: success
    position: below-navbar
  site-url: https://tu-delft-dcc.github.io/
  repo-url: https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io/
  issue-url: https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io/issues/new/choose
  repo-actions: [issue]
  page-navigation: true
  page-footer:
    left: |
      Powered by [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).
    center: |
      &copy; 2024 [TU Delft Digital Competence Centre](https://dcc.tudelft.nl). Licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).
    right: 
          If you find this content useful, please consider giving us a star on GitHub.
          <script async defer src="https://buttons.github.io/buttons.js"></script>
          <a class="github-button" href="https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io" data-icon="star" data-size="small" data-show-count="false" aria-label="Star TU-Delft-DCC/TU-Delft-DCC.github.io on GitHub">Star</a>
    border: false
  bread-crumbs: true # Breadcrumbs in Quarto websites are a type of secondary navigation that shows the user's current location within the site hierarchy
  navbar:
    logo: docs/img/tud/logo_white_crop.png
    collapse-below: lg # It determines at which screen size the navbar should collapse into a mobile-friendly format (typically a hamburger menu)
    right:
      # - href: index.md
      #   text: Overview
      - href: index.md
        text: Guides
      - href: docs/tud-support/index.md
        text: Support Staff
      - href: docs/listing.md
        text: References
      - text: Community
        menu:
          - text: Contributing
            href: CONTRIBUTING.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: About the DCC
            href: https://www.tudelft.nl/library/support/library-voor-onderzoekers/onderzoek-starten/dcc/contact
    tools:
      - icon: github
        href: https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io/
        text: DCC GitHub
  sidebar:
    - title: "Guides"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: "Getting started"
          href: index.md
        - text: <br>
        - section: ⚙️ **Computing Infrastructure**
          contents:
          - section: "Remote servers"
            href: docs/infrastructure/intro_servers.md
            contents:
              - text: Request a VPS
                href: docs/infrastructure/VPS_request.md
              - href: docs/infrastructure/VPS_SSH.md
                text: Configure SSH Tunneling
              - href: docs/infrastructure/moving_data.md
                text: Moving data to your server
              - href: docs/infrastructure/VPS_SSL_Certs.md
                text: Configure SSL certificates
              - href: docs/infrastructure/apache_webserver.md
                text: Setting up an Apache web server
          - section: "TU Delft GitLab" 
            href: docs/infrastructure/gitlab/gitlab_intro.md
            contents:
              - text: Creating GitLab groups
                href: docs/infrastructure/gitlab/gitlab_groups.md
              - text: Transfer ownership of a GitLab repository
                href: docs/infrastructure/gitlab/gitlab_transfer_ownership.md
              - text: Continuous Integration with GitLab
                href: docs/infrastructure/gitlab/gitlab_docker.md
              - text: Setting up a Gitlab runner for MATLAB
                href: docs/infrastructure/gitlab/runner_matlab.md
        - text: <br>
        - section: "🗃️ **Data Management**"
          contents:
            - text: Getting started
              href: docs/data/getting_started.md
            - text: FAIR Data
              href: docs/data/fair_data/fair.md
            - section: Planning
              href: docs/data/planning/planning.md
              contents:
                - text: Privacy and security
                  href: docs/data/planning/privacy_and_security.md
                - text: Ethics
                  href: docs/data/planning/ethics.md
            - section: Data collection
              href: docs/data/data_collection/collection.md
              contents:
                - text: Data conventions
                  href: docs/data/data_collection/data_conventions.md
                - text: Access and reuse
                  href: docs/data/data_collection/access_reuse.md
                - text: eLabJournal and RSpace
                  href: docs/data/data_collection/elab_rspace.md
            - text: Data processing
              href: docs/data/data_processing.md
            - section: Data storage
              href: docs/data/data_storage/storage.md
              contents:
                - text: Storage options
                  href: docs/data/data_storage/storage_options.md
                  contents:
                    - text: Request Project Drive space
                      href: docs/data/data_storage/project_drive_request.md
                    - text: Mount Project Drive on server
                      href: docs/data/data_storage/project_drive_mounting.md
                    - text: Sync Project Drive and SURFDrive with Unison
                      href: docs/data/data_storage/sync_unison.md
                - text: Data security
                  href: docs/data/data_storage/security.md
                - text: Data sharing
                  href: docs/data/data_storage/sharing.md
                - text: Data backup
                  href: docs/data/data_storage/backup.md
            - section: Archival and publishing
              href: docs/data/data_publishing/archival_publishing_index.md
              contents:
                - text: Licensing
                  href: docs/data/data_publishing/licensing_data.md
                - text: Publishing data
                  href: docs/data/data_publishing/publishing.md
                - text: Offboarding and ownership
                  href: docs/data/data_publishing/offboarding.md
        - text: <br>
        - section: "💻 **Research Software**"
          contents:
            - text: Getting started
              href: docs/software/getting_started.md
            - section: "FAIR Software"
              href: docs/software/fair.md
              contents:
                - text: FAIR checklist for research software
                  href: docs/software/checklist.md
                - text: FAIR assessment cards
                  href: docs/software/project_cards.md 
                - text: Software management plan
                  href: docs/software/software_management_plan.md
                - text: FAIR for Research Software Program Spring 2023
                  url: https://tu-delft-dcc.github.io/FAIR4RS/
            - section: "Documentation"
              href: docs/software/documentation/index.md
              contents:
                - text: README
                  href: docs/software/documentation/readme.md
                - text: CITATION.cff
                  href: docs/software/documentation/citation.md
                - text: Software license
                  href: docs/software/documentation/license.md
            - section: "Software testing"
              href: docs/software/testing_intro.md
              contents:
                - text: Testing with MATLAB
                  href: docs/software/testing_matlab.md
            - section: "Version control with git"
              href: docs/software/git/intro.md
              contents:
                - text: Branch management
                  href: docs/software/git/branch_management.md
            - section: "Working with containers"
              href: docs/software/containers/intro.md
              contents:
                - text: Using a docker container with a GUI
                  href: docs/software/containers/docker_gui.md
        - text: <br>
        - section: "📖 **Resources**"
          contents:
            - text: Courses and workshops
              href: docs/resources/courses.md
            - text: Research Software Curriculum
              href: docs/resources/curriculum.md
            - text: Tools
              href: docs/resources/tools.md

    # - title: "TU Delft Support"
    #   contents: 
    #   - href: docs/tud-support/index.md
    #     text: Support at TU Delft
    #   - href: docs/tud-support/partners.md
    #     text: Partners
    #   - href: docs/tud-support/professionalization.md
    #     text: Professionalization

highlight-style: pygments
format:
  html:
    theme: 
      light: 
      - cosmo
      - themes/tud-light.scss
      dark: 
        - solar
        # - themes/tud-dark.scss
    css: themes/custom.css
    lang: en
    toc: true
    toc-location: right
    anchor-sections: true
    smooth-scroll: true
    grid: 
      sidebar-width: 320px
