name: dcc_guides_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - python=3.8
    - pip
    - numpy
    - pandas
    - tabulate
    - jupyter-book
    - sphinx
    - sphinx-tabs
    - sphinx-inline-tabs
    - sphinx-panels
    - sphinx-togglebutton
    - pip:
        - linkify
        - python-frontmatter