#######################################################################################
# Book settings
title: "DCC Guides"
logo: img/logo.png
author: TU Delft Digital Competence Center
email: dcc@tudelft.nl

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"

only_build_toc_files: true

exclude_patterns: [/images/**.*, ./**/*.py, ./**/*.jpg, LICENSE.md]

# Information about where the book exists on the web
repository:
  url: https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io
  branch: master
  path_to_book: docs

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: false
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - replacements
    - tasklist

sphinx:
  config:
    html_show_copyright: false
  extra_extensions:
    - sphinx_inline_tabs
    - sphinx_togglebutton
