name: Deploy guides

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually deploying the jupyterbook
        required: False
        default: ""

jobs:
  deploy:
    name: Deploy jupyter book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx-book-theme --upgrade

      - name: Build table of contents
        run: |
          jupyter-book build ./docs

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
