name: Links (Fail Fast)

on:
  push:
  pull_request:
  
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually checking links
        required: False
        default: ""

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
