name: Scheduled Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * 0" # Runs every Sunday at 20:00 (CEST)

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build Quarto site
        run: quarto render

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: >-
            --exclude-path 'docs/_under_development'
            --exclude-path '_site/docs/_under_development' 
            --accept 429 
            --verbose 
            --no-progress 
            './**/*.md' 
            './**/*.qmd' 
            './**/*.html' 
            # Verbose output and check for both source .md and .qmd files, and then the rendered .html files
          fail: true  # Fail the job if any links are broken
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}